### ISSUE TITLE
Possibly invalid parse or incautious conversion

### ISSUE THREAD

**Issue by adamreichold** [georust/geojson#224]
I am using fallible methods to parse `geojson::Geometry` from untrusted input and convert it into `geo_types::Geometry` for further processing. I hit an unexpected panic for the following test case

```rust
#[test]
fn invalid_parse_or_incautious_conversion() -> Result<(), crate::Error> {
    let geojson: crate::Geometry = std::str::FromStr::from_str(r#"{"type": "Point", "coordinates": []}"#)?;
    let _geomerty: geo_types::Geometry = geojson.try_into()?;
    Ok(())
}
```

which panics with

```
---- conversion::to_geo_types::tests::invalid_parse_or_incautious_conversion stdout ----
thread 'conversion::to_geo_types::tests::invalid_parse_or_incautious_conversion' panicked at 'index out of bounds: the len is 0 but the index is 0', src/conversion/to_geo_types.rs:291:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/panicking.rs:162:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/slice/index.rs:258:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/alloc/src/vec/mod.rs:2691:9
   6: geojson::conversion::to_geo_types::create_geo_point
             at ./src/conversion/to_geo_types.rs:291:17
   7: geojson::conversion::to_geo_types::<impl core::convert::TryFrom<&geojson::geometry::Value> for geo_types::geometry::Geometry<T>>::try_from
             at ./src/conversion/to_geo_types.rs:151:47
   8: <T as core::convert::TryInto<U>>::try_into
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/convert/mod.rs:756:9
   9: geojson::conversion::to_geo_types::<impl core::convert::TryFrom<geojson::geometry::Value> for geo_types::geometry::Geometry<T>>::try_from
             at ./src/conversion/mod.rs:73:17
  10: geojson::conversion::to_geo_types::<impl core::convert::TryFrom<geojson::geometry::Geometry> for geo_types::geometry::Geometry<T>>::try_from
             at ./src/conversion/to_geo_types.rs:213:21
  11: <T as core::convert::TryInto<U>>::try_into
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/convert/mod.rs:756:9
  12: geojson::conversion::to_geo_types::tests::invalid_parse_or_incautious_conversion
             at ./src/conversion/to_geo_types.rs:751:46
  13: geojson::conversion::to_geo_types::tests::invalid_parse_or_incautious_conversion::{{closure}}
             at ./src/conversion/to_geo_types.rs:749:52
  14: core::ops::function::FnOnce::call_once
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/ops/function.rs:250:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/ce5919fcef67103098219e1868f741e56fc90963/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I currently work around this using `catch_unwind` and I would like to try to contribute a fix but I am not sure which part of the crate should be changed. Should `from_str` already fail because a point without coordinates is malformed? Or should `TryInto<geo_types::Geometry>` be more careful when accessing the coordinates of a point?

**Comment by lnicola** [comment]
GDAL rejects 0- and 1-dimensional points and the spec says:

> A position is an array of numbers.  There MUST be two or more elements.

Given that, I think `from_str` should reject this.

**Comment by adamreichold** [comment]
Ok, I will try to work out a fix.
